### ISSUE TITLE
Does raptor-editor work with jQuery 2.10.0? 

### ISSUE THREAD

**Issue by dparsons86** [PANmedia/raptor-editor#159]
I am having troubles getting raptor-editor to work unless I use the no-conflict version. It keeps saying, in my code, that TypeError: $(...).raptor is not a function
And it also says this:
  TypeError: g.widget is not a function
...ct"){k=g.extend(i.options.buttons,k);if(!k.browse){i.browse_button.button("disab...
raptor.js (line 1314)

My code to initialize looks like this:
$('#raptor-editable').raptor();
and I have a div with that name.

My project has jQuery - 2.10.0 and jQuery UI - v1.10.4

I don't really want to use the no-conflict version if I can avoid it, considering my project already has jquery and jquery-ui included.

Thanks!
Daniel
